"""Local LLM inference utilities for QueryEase."""

from __future__ import annotations

import os

from dotenv import load_dotenv
import requests
from requests import Response
from requests.exceptions import ReadTimeout, RequestException

OLLAMA_GENERATE_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "queryease-sql"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 120.0

load_dotenv()


def _get_timeout_seconds() -> float:
	"""Resolve the Ollama request timeout in seconds.

	Returns:
		Timeout value in seconds. Defaults if missing or invalid.
	"""

	raw_timeout = os.getenv("OLLAMA_TIMEOUT_SECONDS", "").strip()
	if not raw_timeout:
		return DEFAULT_OLLAMA_TIMEOUT_SECONDS

	try:
		parsed = float(raw_timeout)
	except ValueError:
		return DEFAULT_OLLAMA_TIMEOUT_SECONDS

	if parsed <= 0:
		return DEFAULT_OLLAMA_TIMEOUT_SECONDS

	return parsed


def _build_prompt(schema_context: str, user_query: str) -> str:
	"""Assemble a prompt that includes schema context and user query.

	Args:
		schema_context: Raw CREATE TABLE statements for the target database.
		user_query: Natural language request to be converted into SQL.

	Returns:
		Full prompt string for the local LLM.
	"""

	return (
		"You are a precise SQL generator. "
		"Return only a valid SQL query; no commentary.\n\n"
		"Database schema:\n"
		f"{schema_context.strip()}\n\n"
		"User request:\n"
		f"{user_query.strip()}\n"
	)


def _parse_ollama_response(response: Response) -> str:
	"""Extract SQL text from an Ollama JSON response.

	Args:
		response: Requests response from the Ollama API.

	Returns:
		SQL string generated by the model.

	Raises:
		RuntimeError: When the response payload is missing SQL output.
	"""

	try:
		payload = response.json()
	except ValueError as exc:
		raise RuntimeError("Ollama returned non-JSON output.") from exc

	sql_output = payload.get("response")
	if not isinstance(sql_output, str) or not sql_output.strip():
		raise RuntimeError("Ollama response did not include SQL output.")

	return sql_output.strip()


def generate_sql(user_query: str, schema_context: str) -> str:
	"""Generate SQL from a user query and live schema context.

	Args:
		user_query: Natural language request from the client.
		schema_context: Live database schema as CREATE TABLE statements.

	Returns:
		SQL query string generated by the local model.

	Raises:
		RuntimeError: When Ollama is unreachable or returns invalid output.
	"""

	prompt = _build_prompt(schema_context=schema_context, user_query=user_query)
	payload = {
		"model": OLLAMA_MODEL,
		"prompt": prompt,
		"stream": False,
	}

	timeout_seconds = max(120.0, _get_timeout_seconds())

	for attempt in range(2):
		try:
			response = requests.post(
				OLLAMA_GENERATE_URL,
				json=payload,
				timeout=timeout_seconds,
			)
			response.raise_for_status()
			break
		except ReadTimeout as exc:
			if attempt == 0:
				print("Ollama cold start detected, retrying...")
				continue
			raise RuntimeError(
				"Ollama request timed out. "
				"Check the service and try again."
			) from exc
		except RequestException as exc:
			raise RuntimeError(
				"Failed to reach Ollama at http://localhost:11434. "
				"Ensure the service is running."
			) from exc

	return _parse_ollama_response(response)
