"""Pydantic schemas for QueryEase API payloads."""

from typing import Literal
from pydantic import BaseModel, ConfigDict


class QueryRequest(BaseModel):
    """Request payload for text-to-SQL generation.

    Attributes:
        user_query: Natural language query text.
        session_id: Client session identifier.
        tenant_id: Tenant identifier for routing and auth context.
        provider: Choice of LLM provider ('local' or 'nim').
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    user_query: str
    session_id: str
    tenant_id: str
    provider: Literal["local", "nim"] = "local"


class QuerySuccessResponse(BaseModel):
    """Successful response for a generated and executed query.

    Attributes:
        status: Status label for the response (always 'success').
        generated_sql: Deterministic SQL generated by the system.
        execution_time_ms: Execution time in milliseconds.
        retries_used: Number of retries used by the self-healing loop.
        data: Query result rows as a list of column-to-value maps.
        inferred_chart_type: Suggested chart type for visualization.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    status: Literal["success"] = "success"
    generated_sql: str
    execution_time_ms: int
    retries_used: int
    data: list[dict[str, object]]
    inferred_chart_type: str


class QueryErrorResponse(BaseModel):
    """Error response for a failed query request.

    Attributes:
        status: Status label for the response (always 'error').
        error_code: Machine-readable error identifier.
        error_message: Human-readable error summary.
        details: Optional structured context for debugging.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    status: Literal["error"] = "error"
    error_code: str
    error_message: str
    details: dict[str, object] | None = None